

source 'git@github.com:HJ2018/HYNBase.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SegmetBar_Example' do
  pod 'SegmetBar', :path => '../'

  target 'SegmetBar_Tests' do
    inherit! :search_paths

    
  end
end
